INFO:root:2025-01-29 16:45:45.937220 - User: admin - Path: /admin/auth/user/
INFO:root:2025-01-29 16:45:45.986371 - User: admin - Path: /admin/jsi18n/
INFO:root:2025-01-29 16:46:01.985998 - User: admin - Path: /admin/auth/group/
INFO:root:2025-01-29 16:46:02.002718 - User: admin - Path: /admin/jsi18n/
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:root:2025-01-29 17:07:35.087274 - User: admin - Path: /admin/auth/group/
ERROR:django.request:Internal Server Error: /admin/auth/group/
Traceback (most recent call last):
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py", line 36, in __call__
    return response(status=status.HTTP_403_FORBIDDEN)
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
INFO:root:2025-01-29 17:07:37.179143 - User: admin - Path: /
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py", line 36, in __call__
    return response(status=status.HTTP_403_FORBIDDEN)
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
INFO:root:2025-01-29 17:07:55.915962 - User: admin - Path: /api/messages
ERROR:django.request:Internal Server Error: /api/messages
Traceback (most recent call last):
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py", line 36, in __call__
    return response(status=status.HTTP_403_FORBIDDEN)
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:root:2025-01-29 17:10:00.901836 - User: admin - Path: /api/messages
ERROR:django.request:Internal Server Error: /api/messages
Traceback (most recent call last):
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:root:2025-01-29 17:12:14.380344 - User: admin - Path: /api/messages
WARNING:django.request:Forbidden: /api/messages
INFO:root:2025-01-29 17:12:19.833849 - User: admin - Path: /api/messages
WARNING:django.request:Forbidden: /api/messages
INFO:root:2025-01-29 17:12:26.003515 - User: admin - Path: /api/conversation
WARNING:django.request:Forbidden: /api/conversation
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:root:2025-01-29 17:15:14.630095 - User: admin - Path: /api/conversation
WARNING:django.request:Not Found: /api/conversation
INFO:root:2025-01-29 17:15:18.626461 - User: admin - Path: /api/conversations/
ERROR:django.request:Internal Server Error: /api/conversations/
Traceback (most recent call last):
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ~~~~~~~~~~~~~~~~~^^
  File "/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 30, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1528, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1342, in check_related_objects
    self.check_query_object_type(value, opts, field)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1319, in check_query_object_type
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Cannot query "admin": Must be "User" instance.
INFO:root:2025-01-29 17:15:36.947403 - User: admin - Path: /api/conversations/
ERROR:django.request:Internal Server Error: /api/conversations/
Traceback (most recent call last):
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ~~~~~~~~~~~~~~~~~^^
  File "/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 30, in get_queryset
    return Conversation.objects.filter(participants=self.request.user)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1528, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1342, in check_related_objects
    self.check_query_object_type(value, opts, field)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/ray/alx/alx-backend-python/backenv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1319, in check_query_object_type
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Cannot query "admin": Must be "User" instance.
INFO:root:2025-01-29 17:15:40.084677 - User: admin - Path: /api/admin
WARNING:django.request:Not Found: /api/admin
INFO:root:2025-01-29 17:15:46.878315 - User: admin - Path: /a
WARNING:django.request:Not Found: /a
INFO:root:2025-01-29 17:15:50.901111 - User: admin - Path: /admin/
INFO:root:2025-01-29 17:15:53.703195 - User: admin - Path: /admin/logout/
INFO:root:2025-01-29 17:15:57.556180 - User: Anonymous - Path: /admin/logout/
INFO:root:2025-01-29 17:15:57.576092 - User: Anonymous - Path: /admin/
INFO:root:2025-01-29 17:15:57.582830 - User: Anonymous - Path: /admin/login/
INFO:root:2025-01-29 17:15:59.227408 - User: Anonymous - Path: /
WARNING:django.request:Not Found: /
INFO:root:2025-01-29 17:16:00.527465 - User: Anonymous - Path: /api/conversations/
WARNING:django.request:Unauthorized: /api/conversations/
INFO:root:2025-01-29 17:16:06.876963 - User: Anonymous - Path: /api/messages
WARNING:django.request:Not Found: /api/messages
INFO:root:2025-01-29 17:16:18.408487 - User: Anonymous - Path: /api/message
WARNING:django.request:Not Found: /api/message
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:root:2025-01-29 17:20:09.774130 - User: Anonymous - Path: /api/conversation-messages
WARNING:django.request:Not Found: /api/conversation-messages
INFO:root:2025-01-29 17:23:33.074014 - User: Anonymous - Path: /api/messages
WARNING:django.request:Not Found: /api/messages
INFO:root:2025-01-29 17:24:39.369252 - User: Anonymous - Path: /api/conversation-messages
WARNING:django.request:Not Found: /api/conversation-messages
INFO:root:2025-01-29 17:25:11.056086 - User: Anonymous - Path: /api/cconversation-messages-list
WARNING:django.request:Not Found: /api/cconversation-messages-list
INFO:root:2025-01-29 17:25:17.623456 - User: Anonymous - Path: /api/conversation-messages-list
WARNING:django.request:Not Found: /api/conversation-messages-list
INFO:root:2025-01-29 17:25:33.836819 - User: Anonymous - Path: /api/
WARNING:django.request:Unauthorized: /api/
INFO:root:2025-01-29 17:25:43.523556 - User: Anonymous - Path: /api/
WARNING:django.request:Unauthorized: /api/
INFO:root:2025-01-29 17:25:46.453882 - User: Anonymous - Path: /api/
WARNING:django.request:Unauthorized: /api/
INFO:root:2025-01-29 17:26:02.331613 - User: Anonymous - Path: /api/conversation
WARNING:django.request:Not Found: /api/conversation
INFO:root:2025-01-29 17:26:08.873009 - User: Anonymous - Path: /api/conversations/
WARNING:django.request:Unauthorized: /api/conversations/
INFO:root:2025-01-29 17:26:35.113447 - User: Anonymous - Path: /api/conversations/
WARNING:django.request:Unauthorized: /api/conversations/
INFO:root:2025-01-29 17:26:54.261326 - User: Anonymous - Path: /api/messages
WARNING:django.request:Not Found: /api/messages
INFO:root:2025-01-29 17:29:41.946851 - User: Anonymous - Path: /api/conversations/messages/
WARNING:django.request:Unauthorized: /api/conversations/messages/
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:root:2025-01-29 17:30:24.302489 - User: Anonymous - Path: /api/conversations/messages/
WARNING:django.request:Unauthorized: /api/conversations/messages/
INFO:root:2025-01-29 17:30:25.791866 - User: Anonymous - Path: /api/conversations/messages/
WARNING:django.request:Unauthorized: /api/conversations/messages/
INFO:root:2025-01-29 17:30:26.737594 - User: Anonymous - Path: /api/conversations/messages/
WARNING:django.request:Unauthorized: /api/conversations/messages/
INFO:django.utils.autoreload:/Users/ray/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
INFO:root:2025-01-29 17:34:34.226914 - User: Anonymous - Path: /api/conversations/messages/
WARNING:django.request:Forbidden: /api/conversations/messages/
INFO:root:2025-01-29 17:34:38.490650 - User: Anonymous - Path: /api/conversations/
WARNING:django.request:Unauthorized: /api/conversations/
